---
title: "Comparing soil nutrients between an annual burned and patch burn grazing system"
author: "Noah Holland"
date: "2023-03-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = '/UNCG_DataWrangling')
```

## Background

text here

## Data Tidying

```{r, load_package, message=FALSE, warning=FALSE}
library(tidyverse)
```

```{r getting data}
rawPBGN <- read.csv("PBG_N_compiled_raw_2021.csv")
rawPBGP <- read.csv("PBG_P_compiled_raw_2021.csv")
rawPBGtrts <- read.csv("PBG_trts.csv")
```

```{r combining P and N datasets}
pbgPN <- rbind(rawPBGP, rawPBGN)
```

```{r filtering data for U# by 'sample'}
FilteredUpgbPN <- pbgPN %>% 
  filter(grepl('U', sample))
```

```{r testing for and removing duplicates}
dim(FilteredUpgbPN)
dim(unique(FilteredUpgbPN))
```

```{r Filtering for max dilution by 'Sample'}
maxDilutionPBG <- FilteredUpgbPN %>% 
  group_by(Sample) %>% 
  filter(dilution == max(dilution, na.rm = TRUE)) %>% 
  ungroup()
```

```{r joining PBG data to treatment data}
PNTreatment <- maxDilutionPBG %>% 
  separate(col = Sample, into = c('watershed', 'transect', 'plot', 'elm'), sep = '-') %>% 
  select(-c(elm)) %>% 
  merge(rawPBGtrts) %>% 
  select(c(treatment, watershed, transect, plot, concentration, units, test)) %>% 
  rename(temp = test) %>% 
  mutate(test = ifelse(temp=="HCl PO4_1",
    "Phosphate",ifelse(temp=="KCL NO3_NO2 2", "Nitrate", "Ammonia"
  )))
```

## Graphs



