library(tidyverse)

morphology<-read.csv("Morphological Trait .csv")
mortality_vascular_epiphytes<-read.csv("Percent mortality for Vascular Epiphytes.csv")
pressure_volume<-read.csv("Pressure Volume Curve Metrics.csv")
vascular_growth<-read.csv("Vascular_Epiphyte_Growth_Number_Leaves.csv")
elaphoglossum_leafsize<-read.csv("Elaphoglossum sp._Growth_Leaf_Length.csv")
foliar_uptake<-read.csv("Foliar Water Uptake Capacity.csv")
spathulifolia_growth<-read.csv("Growth_Pleurothallis spathulifolia_Number_Individuals.csv")
complanata_growth<-read.csv("Growth_Tillandsia complanata_Height.csv")
efficiency_photochemistry<-read.csv("Maximum Efficiency of PSII Photochemistry.csv")
minimum_conductance<-read.csv("Minimal Conductance (Gmin).csv")
dataset<-read.xlsx
this_one<-read.csv("SA02601_v6.csv")

data("airquality")

#Link to data: https://portal.edirepository.org/nis/mapbrowse?packageid=edi.1629.1
# Citation: Anders, E., S. Gotsch, M. Vadeboncoeur, H. Asbjornsen, D. Metcalfe, D. Bartholomew, and A. Horwath. 2025. Leaf traits plus growth and dieback data for cloud forest epiphytes in a cloud exclusion treatment at Wayqecha Biological Station, Peru ver 1. Environmental Data Initiative. https://doi.org/10.6073/pasta/4eb85bc373653c42053b3f38f394cf4e (Accessed 2026-03-15).

#I had trouble finding super dirty data, but this set is pretty all over the place, so I think it will be interesting to try to clean up. Let me know what you think though because I am very open to suggestions.

#Above is all of the data sets that were collected in an experiment to understand how fog in cloud forests influence the epiphytes growing in the area. These measurements were done at the Wayqecha Biological Station in Peru, and experiments were done in two plots. The first plot was a control plot with the typical cloud forest conditions, and the second plot was the experimental or treatment plot that had reduced fog using curtains.I would really like to focus specifically on the data that is about the vascular plants simply because I understand vascular plants better than non-vascular plants. The main question that I would like to ask is how does reduction of fog influence foliar water uptake? Then I am also interested to see if possible changes in water uptake correlate with morphological and physiological traits of the plants. I suspect that as fog lowers, foliar uptake will lower, and epiphytic vascular plants will not grow as much resulting in smaller leaves. Data was collects by harvesting stems and leaves from epiphytic plants 1-2 meters off of the ground. If the plant was in an experimental group it was insured that the specimen was close to the curtain blocking the fog so that plants with he most fog interception were the ones being experimentally evaluated.

#When it comes to cleaning the data, I have a lot of data that is divided into individual sets to work with, so my challenge will be turning all of that information into one data set. The first thing I would want to do is remove all of the data for non-vascular plants, and to remove all data for plant die back since I would like to focus on the phenotypic plasticity on the plant, and I have the PSII photochemistry efficiency to determine stress upon the plant. I would want to sort most of the sets by genus/species, and plot so that it is easier to combine data sets and delete or merge any column that are repetitive. For example ever data set has a plot column. One of my biggest challenges and the plants don't have individual ids, all of the data sets just mark them with the genus and species, but there is no indication of which plants are which between data sets. I am playing with the idea of summarizing the information for each genus because of this, but that might make it difficult to then convert to figures. Since different species were measured in different ways I want to make sure that empty columns are marked with N/A. I then want to combine all of the morphological data sets with the physiological data sets, get rid of any of the repetitive columns.

#When it comes to plotting the data. I really want to show deviation of foliar uptake by making two box plots, one across maybe all of the plants in the control and one of the experimental group to see if there is any overall difference amongst all of the plants. Then I am very interested in a dot plot using the PSII Photochemistry data and the foliar uptake. And then I would like to make a histogram that looks at physiological changes, and how much the plant grew based on if it is a control plant or experimental plant.

#*There is so much going on with the data that hopefully peer and professor evaluations will really help me narrow down the data and all my possibilities to what will be the most productive.


#individual project take 2
#link:https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-and.5216.8
#Citation:Seo, E., J.A. Jones, R.A. Hutchinson, and V.W. Pfeiffer. 2022. Plant Pollinator data at HJ Andrews Experimental Forest, 2011 to 2021 ver 8. Environmental Data Initiative. https://doi.org/10.6073/pasta/eec55cbc3dbfc56428629773737ab3e5 (Accessed 2026-03-15).

#This is a set of data that is a record of plants and their pollinators an how environmental factors such as soil moisture, temperature, and size of a meadow influences plant/pollinator relationships.Based on the data set the data was recorded by having someone watch a meadow and observe the plants in the meadow, and each time there was a pollinator and plant interaction a new observation was logged. Most meadow watches seemed to be about 3min, but it varies between person it looks like. This data set along with other collected by this set of people was done to add to the limited amount of long term recorded data about plant/pollinator relationships.This data was collected from 18 meadows in the Willamette national forest which is located in Oregon. Although the overall experiments tests influence of meadow size and soil moisture, the data set used for this project primarily records occurrence of plant pollinator interactions. Weather and wind measurements are consistently recorded throughout the data set, but temperature is not. There are large gaps throughout the data set that is missing temperature data which means I will be focusing on how temperature influences pollinators rather than the plants themselves since I do not have that soil temp recording. 

#Some things that I am interested in looking it as the the relationship between abiotic and biotic factors. I wonder if there is a correlation between wind or clouds and what type of insects visit the plant. My suspicion is that there will be less pollinators on windier days and cloudier days. I would also like to look at the types of insects that visit each type of plant.From a brief look at the data it looks like the genus Epicauta primarily has fly and beetle visitors rather than bee visitors.Although I am not provided info about the size of each meadow in this data set, I can compare the different meadows and plots to see differences in species diversity between them, and because this is a long term study I suspect that there will be plant diversity differences between the years.So, another one of my question is how has plant and pollinator diversity shifted overtime, and which meadows have more diversity, and which have less.

#When it comes to cleaning this data the first thing I would do is remove any information that is extra or unnecessary for the end dataset. That means columns such as DBCode and entity will be merged, observer will be removed, notes will be removed. All of the id information might be condensed so that there is less visual clutter. For example there is both a plotId and plot column when the plotId includes the plot column so there does not need to be both. I will want to move the minute observed closer to the species of the plant and visitor. I also am going to figure out what plant species there is the most data for and use that species of plant as the basis for my figures. There are some variables that I do not understand what they mean so I will change the contents of wind and clouds to contain descriptions that make more sense. I will get rid of the species code and visitor code columns and change the names of the species name and visitor name to be easier to understand.I then want to take the data and produce a histogram that shows how many insects visit each  species of plant. Then I would also like to make a dot plot that shows # of insects that arrive on a temperature gradient. To look at diversity overtime, I might need to make a mini dataset that contains summaries of how many occurrences per meadow per year there are, and this would be another data set that would benefit from choosing one species of plant rather than the many included in this data set.

