---
title: 'TEMPEST: Understory plant community responses to coastal flooding'
author: "Zachary Bunch"
date: "3/19/2023"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir= '/tmp')
library(tidyverse)

```
## Set up
Load tidyverse and setup R.

## Background

Destructive weather phenomenons are becoming more commonplace as global climate change intensifies. Researchers at the Smithsonian designed an experiment to investigates how heavy flooding or rapid downpours impact forest ecosystems. The experiment will emulate forest flooding from both fresh and salt water disruptions. 

Three plots were used to explore the impact of flooding on the under story community. Prior to experimentation, the species cover for each plot was determined, allowing for a point of comparison. Experimental observations were taken as approximate percent cover within a small subplot. The three large plots were 40 x 50 m (C, F and S) with each containing 16 subplots. A special "additional" subplot was created for species found but not sampled.  

```
TEMPEST <- read.csv("TEMPEST_SERC_understory sppcomp_2021.csv")


# Select only rows of the data frame that correspond to plant species
is_plant <- !grepl("infrastructure|cover", TEMPEST$species)

# Subset the data frame using the is_plant vector
plant_species <- TEMPEST[is_plant, "species", drop = FALSE]

# Remove duplicate species names
plant_species <- unique(plant_species)

# Subset the TEMPEST data frame to only include treatment columns
treatment_info <- TEMPEST[, c("project_name", "calendar_year", "treatment_year", "season", "plot", "subplot")]

# Create a new column for replicate
treatment_info$replicate <- paste(treatment_info$plot, treatment_info$subplot, sep = "_")

# Create a new column for verbalized plot treatment
treatment_info$treatment <- ifelse(TEMPEST$plot == "C", "C", 
                                    ifelse(TEMPEST$plot == "S", "S",
                                           ifelse(TEMPEST$plot == "F", "F", NA)))

# Remove the plot and subplot columns
treatment_info$plot <- treatment_info$subplot <- NULL


```
# Code Chunk 1.1
We first read in the TEMPEST_SERC_understory sppcomp_2021.csv file into the variable TEMPEST. !Grepl selects the correct data frames and those data frames are then taken as a subset from the TEMPEST data frame. We than utilize the unique function to ensure that we only have unique values. The paste function is utilized to combine plot and subset into a new column called replicate. Additionally, a new column also created called treatment that utilizes a ifelse statement to extract treatment information from the appropriately labeled column in TEMPEST. Finally, the plot and subplot column are removed for simplicity. 



```
library(dplyr)

# Select only rows of the data frame that correspond to plant species
is_plant <- !grepl("infrastructure|cover", TEMPEST$species)

# Subset the data frame using the is_plant vector
TEMPEST_plants <- TEMPEST[is_plant, ]

# Remove rows with "additional" in subplot column
TEMPEST_plants <- TEMPEST_plants %>% filter(!grepl("additional", subplot))

# Calculate total herbaceous plant cover for each subplot
total_cover <- TEMPEST_plants %>%
  group_by(subplot) %>%
  summarize(total_cover = sum(cover))

# Join total_cover data frame back to the original data frame
TEMPEST_cover <- TEMPEST_plants %>% left_join(total_cover, by = "subplot")

# Calculate relative cover for each species
TEMPEST_cover <- TEMPEST_cover %>%
  mutate(relative_cover = 100 * cover / total_cover)


```

## Code Chunk 1.2

We are once again using our is_plant variable to get only plant values (not infrastructure or cover). We then use the is_plant variable to select only the rows of data containing real plants. We then utilize grepl to remove the "additional" subplot from the subplot column. We than use a group_by statement to group by subplot and sum the cover data for each subplot. Then, we join the total_cover back to TEMPEST_plants are store in it TEMPEST_cover. Finally, we create a column storing calculating and storing the relative cover in the TEMPEST_cover variable. 

```
#Richness 

subplot_species_richness <- TEMPEST_plants %>%
  group_by(subplot) %>%
  summarize(species_richness = n_distinct(species))


#Richness mean and standrad error

plot_species_richness <- subplot_species_richness %>%
  group_by(plot) %>%
  summarize(mean_species_richness = mean(species_richness),
            se_species_richness = sd(species_richness) / sqrt(n()))
            
            
plot_species_richness_all <- TEMPEST_plants %>%
  group_by(plot) %>%
  summarize(species_richness = n_distinct(species, na.rm = TRUE))            
  
  
```

## Code Chunk 1.3

subplot_species_richness is created by calling TEMPEST_plants, grouping by subplot and utilizing the summarize function to store n_distict (number of unique species) in a column called species_richness. 

plot_species_richness calls the subplot_species_richness variable and groups by plot. Then, we use the summarize function to calculate the mean of species_richness as well as the standard error. 

Lastly, we create plot_species_richness_all by calling the TEMPEST_plants variable, grouping by plot, using summarize to determine n_distinct for the number of species (species richness).

```
#Bar graph

subplot_plot_richness <- plot_species_richness %>%
  ggplot(aes(x = plot, y = mean_species_richness)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  geom_errorbar(aes(ymin = mean_species_richness - se_species_richness, ymax = mean_species_richness +     se_species_richness), width = 0.4) +
  ggtitle("Mean subplot species richness per plot") +
  xlab("Plot") + ylab("Mean species richness")
  
plot(subplot_plot_richness)

  
plot_richness_plot <- ggplot(plot_species_richness_all, aes(x = plot, y = species_richness)) +
  geom_bar(stat = "identity", fill = "steelblue", alpha = 0.8) +
  labs(title = "Richness at the plot level", x = "Plot", y = "Richness")

plot(plot_richness_plot)
  
```
## Code Chunk 1.4

First graph displays richness per plot using mean of subplots. Made using a ggplot function and stored in subplot_plot_richness. Second graph displays richness at the plot level. Also uses ggplot function and stores output in the varible plot_richness_plot. 

```
#Average Relative cover for each species

plot_species_cover <- TEMPEST %>%
  filter(!grepl("infrastructure|cover", species)) %>%
  group_by(plot, species) %>%
  summarize(total_cover = sum(cover)) %>%
  mutate(relative_cover = 100 * total_cover / sum(total_cover)) %>%
  ungroup()

avg_species_cover <- plot_species_cover %>%
  group_by(species) %>%
  summarize(avg_relative_cover = mean(relative_cover))

plot_species_cover2 <- avg_species_cover %>%
  arrange(desc(avg_relative_cover))
  
plot_species_cover3 <- plot_species_cover2 %>%
  arrange(desc(avg_relative_cover)) %>%
  mutate(rank = rank(-avg_relative_cover, ties.method = "min"))  

ggplot(plot_species_cover3, aes(x = rank, y = avg_relative_cover, group = 1)) +
  geom_line() +
  geom_point() +
  geom_text(aes(label = species), size = 2, angle = 330, vjust = -0.5, hjust = 1) +
  scale_x_reverse() +
  xlab("Rank") +
  ylab("Average Relative Cover (%)") +
  ggtitle("Rank Abundance Curve for Understory Plant Community") +
  ylim(0, 55)



```
## Code Chunk 1.5

We calculated the average relative cover for each species in their subplots. Then, we calculated the average cover for species across plots. Then, we placed them in descending order and added a column providing each species with a rank. Then we created a plot that displayed the ranked abundance. Hence, a ranked abundance curve. 

```
species_we_need <- c("Berberis thunbergii", "Botrychium dissectum", "Carex sp", "Elaeagnus umbellata", 
                         "Epifagus virginiana", "Gallium circaezans", "Ilex opaca", "Lindera benzoin",
                         "Lonicera japonica", "Mitchella repens", "Parthenocissus quinquefolia", 
                         "Polygonum virginianum", "Rhus radicans", "Rubus phoenicolasius", 
                         "Sceptridium biternatum", "Symphotrichium lateriflorum")
                         
species_mean_se <- TEMPEST %>%
  filter(species %in% species_we_need) %>%
  group_by(plot, species) %>%
  summarize(avg_species_cover = mean(relative_cover),
            se_relative_cover = sd(relative_cover) / sqrt(n())) %>%
  ungroup()


ggplot(species_mean_se, aes(x = plot, y = avg_species_cover, fill = species)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin = avg_species_cover - se_relative_cover, 
                    ymax = avg_species_cover + se_relative_cover), 
                position = position_dodge(width = 0.9), width = 0.2) +
  facet_wrap(~ species, scales = "free_y") +
  labs(x = "Plot", y = "Mean Relative Cover (%)", fill = "Species") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```
## Code Chunk 1.6 ####

species_we_need holds a vector contain the species we want to target. species_mean_se pulls TEMPEST data to calculate average species coverage and standard error. We then use ggplot to create a meaningful graphic displaying this data.

## Summary ####

In lieu of any statistical modeling, we can view our rank abundance curve to understand which plant dominates our understory. The clear winner is Mitchella repens, with over 48% relative cover, indicating that it is dominating the understory. 

In our plot from Code Chunk 1.6 we can see that there is SIGNIFICANT variation across the performance of species based on which treatment they are a part of. Broadly, this gives us insight into the effects of saltwater and freshwater flooding. If species are responding differently, which they are, this indicates that both saltwater and freshwater flooding/downpour would have the potential to significantly alter and potentially devastate these ecological communities. 

In terms of richness, our freshwater treatment appears to be the highest. However, it is closely matched with our control and may not be significantly different. Additionally, saltwater flooding seemed to have a meaningful impact on richness. Lastly, is important to remember that equal richness does not necessarily indicate that no community restructing has occurred. Are the species present in similar abundance as they were previously? Are they even the same species?

Broadly, these data highlight the dangers of flooding brought on by global change. It appears that continuous research to identify future and current risks is needed. Furthermore, research targeting full or partial solutions may be a route to consider. 
